# Numpy

- used for n dimensional array
- It provides support for large, multi-dimensional arrays and matrices

In [3]:
!pip install numpy

In [5]:
import numpy as np

# Creating a array

In [19]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [21]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [23]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Initial Placeholder:

1. Zeros():

- Two create an entire array with zeros 

In [32]:
c=np.zeros([3,4,5]) # syntax : shape,rows,colums
print(c)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [36]:
c=np.zeros([1,2,5]) # syntax : shape,rows,colums
print(c)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [38]:
c=np.zeros([3,2,2]) # syntax : shape,rows,colums
print(c)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [47]:
c=np.zeros([2,2,5]) # syntax : shape,rows,colums
print(c)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [44]:
c=np.zeros([1,2,2]) # syntax : shape,rows,colums
print(c)

[[[0. 0.]
  [0. 0.]]]


2.for ones:

- Two create an entire array with ones

In [55]:
b=np.ones([2,3,4]) # shape,row,column
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [57]:
b=np.ones([1,3,4]) # shape,row,column
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [59]:
b=np.ones([3,4]) # shape,row,column
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [61]:
b=np.ones([0,3,4]) # shape,row,column
print(b)

[]


In [63]:
b=np.ones([2,2,4]) # shape,row,column
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [65]:
b=np.ones([2,3,6]) # shape,row,column
print(b)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


3.for creating evenly spaced values:

In [92]:
d=np.arange(1,20,5)  # [start value,end value,step]
print(d)              #[step = n-1,  5-1=4] skips 4 values and print the next value 

[ 1  6 11 16]


In [98]:
d=np.arange(1,10,6)  # [start value,end value,step]
print(d)              #[step = n-1,  6-1=5] skips 4 values and print the next value 

[1 7]


In [100]:
d=np.arange(1,15,3)  # [start value,end value,step]
print(d)              #[step = n-1,  3-1=2] skips 4 values and print the next value 

[ 1  4  7 10 13]


In [102]:
d=np.arange(1,100,2)  # [start value,end value,step]
print(d)              #[step = n-1,  2-1=1] skips 4 values and print the next value 

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


4.for evenly spaced samples:

In [105]:
s=np.linspace(1,10,20)     # [starting,ending , how many ]
print(s)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [107]:
s=np.linspace(1,100,20)     # [starting,ending , how many ]
print(s)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [109]:
s=np.linspace(1,15,2)     # [starting,ending , how many times ]
print(s)

[ 1. 15.]


In [111]:
s=np.linspace(1,16,20)     # [starting,ending , how many times ]
print(s)

[ 1.          1.78947368  2.57894737  3.36842105  4.15789474  4.94736842
  5.73684211  6.52631579  7.31578947  8.10526316  8.89473684  9.68421053
 10.47368421 11.26315789 12.05263158 12.84210526 13.63157895 14.42105263
 15.21052632 16.        ]


In [113]:
s=np.linspace(1,150,20)     # [starting,ending , how many times ]
print(s)

[  1.           8.84210526  16.68421053  24.52631579  32.36842105
  40.21052632  48.05263158  55.89473684  63.73684211  71.57894737
  79.42105263  87.26315789  95.10526316 102.94736842 110.78947368
 118.63157895 126.47368421 134.31578947 142.15789474 150.        ]
